# Test HTTP requests
### use with: REST Client extension

### GET all items
GET http://localhost:3000/items

### Add new item
POST http://localhost:3000/items
Content-Type: application/json

{"name": "Mandariini"}