# Test HTTP requests
### use with: REST Client extension
@apiurl = http://localhost:3000/api

### GET all items
GET {{apiurl}}/items

### GET item with id 1
GET {{apiurl}}/items/1

### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{"name": "Mandariini", "weight": 86}

### Delete item with id 2
DELETE {{apiurl}}/items/2

### Update item with id 1
PUT {{apiurl}}/items/1
Content-Type: application/json

{"name": "updated Omena"}

##############################
### users endpoints

### Get all users
GET {{apiurl}}/users

### Register new user
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "donald",
  "password": "duck",
  "email": "donald@example.com"
}

### Register new user FAIL (email missing)
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "donald",
  "password": "duck"
}

### User login
POST {{apiurl}}/users/login
Content-Type: application/json

{
  "username": "bob_brown",
  "password": "hashed_password"
}


##############################
### Diary entry endpoints

### Get all entries
GET {{apiurl}}/entries

### Get entry by id
GET {{apiurl}}/entries/6

### Post new entry
POST {{apiurl}}/entries
Content-Type: application/json

{
  "user_id": 3,
  "entry_date": "2026-02-04",
  "mood": "really happy",
  "weight": 66,
  "sleep_hours": 5,
  "notes": "normipäivä"
}